// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -package authenticating -typed -destination mock_deps_test.go
//

// Package authenticating is a generated GoMock package.
package authenticating

import (
	context "context"
	reflect "reflect"

	model "github.com/inna-maikut/avito-shop/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockemployeeRepo is a mock of employeeRepo interface.
type MockemployeeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockemployeeRepoMockRecorder
}

// MockemployeeRepoMockRecorder is the mock recorder for MockemployeeRepo.
type MockemployeeRepoMockRecorder struct {
	mock *MockemployeeRepo
}

// NewMockemployeeRepo creates a new mock instance.
func NewMockemployeeRepo(ctrl *gomock.Controller) *MockemployeeRepo {
	mock := &MockemployeeRepo{ctrl: ctrl}
	mock.recorder = &MockemployeeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockemployeeRepo) EXPECT() *MockemployeeRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockemployeeRepo) Create(ctx context.Context, username, passwordHash string, balance int64) (*model.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, username, passwordHash, balance)
	ret0, _ := ret[0].(*model.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockemployeeRepoMockRecorder) Create(ctx, username, passwordHash, balance any) *MockemployeeRepoCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockemployeeRepo)(nil).Create), ctx, username, passwordHash, balance)
	return &MockemployeeRepoCreateCall{Call: call}
}

// MockemployeeRepoCreateCall wrap *gomock.Call
type MockemployeeRepoCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockemployeeRepoCreateCall) Return(arg0 *model.Employee, arg1 error) *MockemployeeRepoCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockemployeeRepoCreateCall) Do(f func(context.Context, string, string, int64) (*model.Employee, error)) *MockemployeeRepoCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockemployeeRepoCreateCall) DoAndReturn(f func(context.Context, string, string, int64) (*model.Employee, error)) *MockemployeeRepoCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByUsername mocks base method.
func (m *MockemployeeRepo) GetByUsername(ctx context.Context, username string) (*model.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(*model.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockemployeeRepoMockRecorder) GetByUsername(ctx, username any) *MockemployeeRepoGetByUsernameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockemployeeRepo)(nil).GetByUsername), ctx, username)
	return &MockemployeeRepoGetByUsernameCall{Call: call}
}

// MockemployeeRepoGetByUsernameCall wrap *gomock.Call
type MockemployeeRepoGetByUsernameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockemployeeRepoGetByUsernameCall) Return(arg0 *model.Employee, arg1 error) *MockemployeeRepoGetByUsernameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockemployeeRepoGetByUsernameCall) Do(f func(context.Context, string) (*model.Employee, error)) *MockemployeeRepoGetByUsernameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockemployeeRepoGetByUsernameCall) DoAndReturn(f func(context.Context, string) (*model.Employee, error)) *MockemployeeRepoGetByUsernameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MocktokenProvider is a mock of tokenProvider interface.
type MocktokenProvider struct {
	ctrl     *gomock.Controller
	recorder *MocktokenProviderMockRecorder
}

// MocktokenProviderMockRecorder is the mock recorder for MocktokenProvider.
type MocktokenProviderMockRecorder struct {
	mock *MocktokenProvider
}

// NewMocktokenProvider creates a new mock instance.
func NewMocktokenProvider(ctrl *gomock.Controller) *MocktokenProvider {
	mock := &MocktokenProvider{ctrl: ctrl}
	mock.recorder = &MocktokenProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenProvider) EXPECT() *MocktokenProviderMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MocktokenProvider) CreateToken(username string, userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", username, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MocktokenProviderMockRecorder) CreateToken(username, userID any) *MocktokenProviderCreateTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MocktokenProvider)(nil).CreateToken), username, userID)
	return &MocktokenProviderCreateTokenCall{Call: call}
}

// MocktokenProviderCreateTokenCall wrap *gomock.Call
type MocktokenProviderCreateTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocktokenProviderCreateTokenCall) Return(arg0 string, arg1 error) *MocktokenProviderCreateTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocktokenProviderCreateTokenCall) Do(f func(string, int64) (string, error)) *MocktokenProviderCreateTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocktokenProviderCreateTokenCall) DoAndReturn(f func(string, int64) (string, error)) *MocktokenProviderCreateTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
