// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -package info_collecting -typed -destination mock_deps_test.go
//

// Package info_collecting is a generated GoMock package.
package info_collecting

import (
	context "context"
	reflect "reflect"

	model "github.com/inna-maikut/avito-shop/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockemployeeRepo is a mock of employeeRepo interface.
type MockemployeeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockemployeeRepoMockRecorder
}

// MockemployeeRepoMockRecorder is the mock recorder for MockemployeeRepo.
type MockemployeeRepoMockRecorder struct {
	mock *MockemployeeRepo
}

// NewMockemployeeRepo creates a new mock instance.
func NewMockemployeeRepo(ctrl *gomock.Controller) *MockemployeeRepo {
	mock := &MockemployeeRepo{ctrl: ctrl}
	mock.recorder = &MockemployeeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockemployeeRepo) EXPECT() *MockemployeeRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockemployeeRepo) GetByID(ctx context.Context, employeeID int64) (*model.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, employeeID)
	ret0, _ := ret[0].(*model.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockemployeeRepoMockRecorder) GetByID(ctx, employeeID any) *MockemployeeRepoGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockemployeeRepo)(nil).GetByID), ctx, employeeID)
	return &MockemployeeRepoGetByIDCall{Call: call}
}

// MockemployeeRepoGetByIDCall wrap *gomock.Call
type MockemployeeRepoGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockemployeeRepoGetByIDCall) Return(arg0 *model.Employee, arg1 error) *MockemployeeRepoGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockemployeeRepoGetByIDCall) Do(f func(context.Context, int64) (*model.Employee, error)) *MockemployeeRepoGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockemployeeRepoGetByIDCall) DoAndReturn(f func(context.Context, int64) (*model.Employee, error)) *MockemployeeRepoGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MocktransactionRepo is a mock of transactionRepo interface.
type MocktransactionRepo struct {
	ctrl     *gomock.Controller
	recorder *MocktransactionRepoMockRecorder
}

// MocktransactionRepoMockRecorder is the mock recorder for MocktransactionRepo.
type MocktransactionRepoMockRecorder struct {
	mock *MocktransactionRepo
}

// NewMocktransactionRepo creates a new mock instance.
func NewMocktransactionRepo(ctrl *gomock.Controller) *MocktransactionRepo {
	mock := &MocktransactionRepo{ctrl: ctrl}
	mock.recorder = &MocktransactionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktransactionRepo) EXPECT() *MocktransactionRepoMockRecorder {
	return m.recorder
}

// GetByEmployee mocks base method.
func (m *MocktransactionRepo) GetByEmployee(ctx context.Context, employeeID int64) ([]model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmployee", ctx, employeeID)
	ret0, _ := ret[0].([]model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmployee indicates an expected call of GetByEmployee.
func (mr *MocktransactionRepoMockRecorder) GetByEmployee(ctx, employeeID any) *MocktransactionRepoGetByEmployeeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmployee", reflect.TypeOf((*MocktransactionRepo)(nil).GetByEmployee), ctx, employeeID)
	return &MocktransactionRepoGetByEmployeeCall{Call: call}
}

// MocktransactionRepoGetByEmployeeCall wrap *gomock.Call
type MocktransactionRepoGetByEmployeeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocktransactionRepoGetByEmployeeCall) Return(arg0 []model.Transaction, arg1 error) *MocktransactionRepoGetByEmployeeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocktransactionRepoGetByEmployeeCall) Do(f func(context.Context, int64) ([]model.Transaction, error)) *MocktransactionRepoGetByEmployeeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocktransactionRepoGetByEmployeeCall) DoAndReturn(f func(context.Context, int64) ([]model.Transaction, error)) *MocktransactionRepoGetByEmployeeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockinventoryRepo is a mock of inventoryRepo interface.
type MockinventoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockinventoryRepoMockRecorder
}

// MockinventoryRepoMockRecorder is the mock recorder for MockinventoryRepo.
type MockinventoryRepoMockRecorder struct {
	mock *MockinventoryRepo
}

// NewMockinventoryRepo creates a new mock instance.
func NewMockinventoryRepo(ctrl *gomock.Controller) *MockinventoryRepo {
	mock := &MockinventoryRepo{ctrl: ctrl}
	mock.recorder = &MockinventoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinventoryRepo) EXPECT() *MockinventoryRepoMockRecorder {
	return m.recorder
}

// GetByEmployee mocks base method.
func (m *MockinventoryRepo) GetByEmployee(ctx context.Context, employeeID int64) ([]model.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmployee", ctx, employeeID)
	ret0, _ := ret[0].([]model.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmployee indicates an expected call of GetByEmployee.
func (mr *MockinventoryRepoMockRecorder) GetByEmployee(ctx, employeeID any) *MockinventoryRepoGetByEmployeeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmployee", reflect.TypeOf((*MockinventoryRepo)(nil).GetByEmployee), ctx, employeeID)
	return &MockinventoryRepoGetByEmployeeCall{Call: call}
}

// MockinventoryRepoGetByEmployeeCall wrap *gomock.Call
type MockinventoryRepoGetByEmployeeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockinventoryRepoGetByEmployeeCall) Return(arg0 []model.Inventory, arg1 error) *MockinventoryRepoGetByEmployeeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockinventoryRepoGetByEmployeeCall) Do(f func(context.Context, int64) ([]model.Inventory, error)) *MockinventoryRepoGetByEmployeeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockinventoryRepoGetByEmployeeCall) DoAndReturn(f func(context.Context, int64) ([]model.Inventory, error)) *MockinventoryRepoGetByEmployeeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
