// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -package coin_sending -typed -destination mock_deps_test.go
//

// Package coin_sending is a generated GoMock package.
package coin_sending

import (
	context "context"
	reflect "reflect"

	model "github.com/inna-maikut/avito-shop/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MocktrManager is a mock of trManager interface.
type MocktrManager struct {
	ctrl     *gomock.Controller
	recorder *MocktrManagerMockRecorder
}

// MocktrManagerMockRecorder is the mock recorder for MocktrManager.
type MocktrManagerMockRecorder struct {
	mock *MocktrManager
}

// NewMocktrManager creates a new mock instance.
func NewMocktrManager(ctrl *gomock.Controller) *MocktrManager {
	mock := &MocktrManager{ctrl: ctrl}
	mock.recorder = &MocktrManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktrManager) EXPECT() *MocktrManagerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MocktrManager) Do(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MocktrManagerMockRecorder) Do(ctx, fn any) *MocktrManagerDoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MocktrManager)(nil).Do), ctx, fn)
	return &MocktrManagerDoCall{Call: call}
}

// MocktrManagerDoCall wrap *gomock.Call
type MocktrManagerDoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocktrManagerDoCall) Return(err error) *MocktrManagerDoCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocktrManagerDoCall) Do(f func(context.Context, func(context.Context) error) error) *MocktrManagerDoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocktrManagerDoCall) DoAndReturn(f func(context.Context, func(context.Context) error) error) *MocktrManagerDoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockemployeeRepo is a mock of employeeRepo interface.
type MockemployeeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockemployeeRepoMockRecorder
}

// MockemployeeRepoMockRecorder is the mock recorder for MockemployeeRepo.
type MockemployeeRepoMockRecorder struct {
	mock *MockemployeeRepo
}

// NewMockemployeeRepo creates a new mock instance.
func NewMockemployeeRepo(ctrl *gomock.Controller) *MockemployeeRepo {
	mock := &MockemployeeRepo{ctrl: ctrl}
	mock.recorder = &MockemployeeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockemployeeRepo) EXPECT() *MockemployeeRepoMockRecorder {
	return m.recorder
}

// GetByIDWithLock mocks base method.
func (m *MockemployeeRepo) GetByIDWithLock(ctx context.Context, employeeID int64) (*model.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDWithLock", ctx, employeeID)
	ret0, _ := ret[0].(*model.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDWithLock indicates an expected call of GetByIDWithLock.
func (mr *MockemployeeRepoMockRecorder) GetByIDWithLock(ctx, employeeID any) *MockemployeeRepoGetByIDWithLockCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDWithLock", reflect.TypeOf((*MockemployeeRepo)(nil).GetByIDWithLock), ctx, employeeID)
	return &MockemployeeRepoGetByIDWithLockCall{Call: call}
}

// MockemployeeRepoGetByIDWithLockCall wrap *gomock.Call
type MockemployeeRepoGetByIDWithLockCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockemployeeRepoGetByIDWithLockCall) Return(arg0 *model.Employee, arg1 error) *MockemployeeRepoGetByIDWithLockCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockemployeeRepoGetByIDWithLockCall) Do(f func(context.Context, int64) (*model.Employee, error)) *MockemployeeRepoGetByIDWithLockCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockemployeeRepoGetByIDWithLockCall) DoAndReturn(f func(context.Context, int64) (*model.Employee, error)) *MockemployeeRepoGetByIDWithLockCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByUsername mocks base method.
func (m *MockemployeeRepo) GetByUsername(ctx context.Context, username string) (*model.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(*model.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockemployeeRepoMockRecorder) GetByUsername(ctx, username any) *MockemployeeRepoGetByUsernameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockemployeeRepo)(nil).GetByUsername), ctx, username)
	return &MockemployeeRepoGetByUsernameCall{Call: call}
}

// MockemployeeRepoGetByUsernameCall wrap *gomock.Call
type MockemployeeRepoGetByUsernameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockemployeeRepoGetByUsernameCall) Return(arg0 *model.Employee, arg1 error) *MockemployeeRepoGetByUsernameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockemployeeRepoGetByUsernameCall) Do(f func(context.Context, string) (*model.Employee, error)) *MockemployeeRepoGetByUsernameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockemployeeRepoGetByUsernameCall) DoAndReturn(f func(context.Context, string) (*model.Employee, error)) *MockemployeeRepoGetByUsernameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MocktransactionRepo is a mock of transactionRepo interface.
type MocktransactionRepo struct {
	ctrl     *gomock.Controller
	recorder *MocktransactionRepoMockRecorder
}

// MocktransactionRepoMockRecorder is the mock recorder for MocktransactionRepo.
type MocktransactionRepoMockRecorder struct {
	mock *MocktransactionRepo
}

// NewMocktransactionRepo creates a new mock instance.
func NewMocktransactionRepo(ctrl *gomock.Controller) *MocktransactionRepo {
	mock := &MocktransactionRepo{ctrl: ctrl}
	mock.recorder = &MocktransactionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktransactionRepo) EXPECT() *MocktransactionRepoMockRecorder {
	return m.recorder
}

// GetByEmployee mocks base method.
func (m *MocktransactionRepo) GetByEmployee(ctx context.Context, employeeID int64) ([]model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmployee", ctx, employeeID)
	ret0, _ := ret[0].([]model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmployee indicates an expected call of GetByEmployee.
func (mr *MocktransactionRepoMockRecorder) GetByEmployee(ctx, employeeID any) *MocktransactionRepoGetByEmployeeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmployee", reflect.TypeOf((*MocktransactionRepo)(nil).GetByEmployee), ctx, employeeID)
	return &MocktransactionRepoGetByEmployeeCall{Call: call}
}

// MocktransactionRepoGetByEmployeeCall wrap *gomock.Call
type MocktransactionRepoGetByEmployeeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocktransactionRepoGetByEmployeeCall) Return(arg0 []model.Transaction, arg1 error) *MocktransactionRepoGetByEmployeeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocktransactionRepoGetByEmployeeCall) Do(f func(context.Context, int64) ([]model.Transaction, error)) *MocktransactionRepoGetByEmployeeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocktransactionRepoGetByEmployeeCall) DoAndReturn(f func(context.Context, int64) ([]model.Transaction, error)) *MocktransactionRepoGetByEmployeeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
